import Head from 'next/head'

import Box from '@mui/material/Box'

import Navbar from '../components/Navbar'
import HomeContent from '../components/HomeContent'

const desktopBg = `/images/background-home-desktop.jpg`
const tabletBg = `/images/background-home-tablet.jpg`

export default function Home() {
  return (
    <Box
      sx={{
        backgroundImage: {
          xs: `url(${tabletBg}) `,
          lg: `url(${desktopBg}) `
        },

        height: '100vh',
        position: 'fixed',
        top: 0,
        left: 0,
        /* Préserve le ratio de l'image */
        minWidth: '100%',
        minHeight: '100%',
        backgroundSize: 'cover'
      }}
    >
      <Head>
        <title>Space tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@200;300;400;600&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <HomeContent />
    </Box>
  )
}
