import Head from 'next/head'
import Image from 'next/image'

import Button from '@mui/material/Button'
import Fab from '@mui/material/Fab'
import NavigationIcon from '@mui/icons-material/Navigation'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Space tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Button variant="contained">Contained</Button>
      <Fab variant="extended">
        <NavigationIcon sx={{ mr: 1 }} />
        Navigate
      </Fab> */}
      <Image
        alt="earth view"
        src="/images/background-home-desktop.jpg"
        layout="fill"
      />
    </div>
  )
}
