import Head from 'next/head'

import Navbar from '../components/Navbar'
import HomeContent from './HomeContent'

export default function Home() {
  return (
    <div
      style={{
        background: `url(/images/background-home-desktop.jpg) `,
        height: '100vh',
        position: 'fixed',
        top: 0,
        left: 0,
        /* Préserve le ratio de l'image */
        minWidth: '100%',
        minHeight: '100%',
        backgroundSize: 'cover'
      }}
    >
      <Head>
        <title>Space tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Bellefair&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@200;300;400;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <HomeContent />
    </div>
  )
}
